name: Deploy on production

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build and push statics over ssh
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.4.2
    - name: Deploy
      env:
        key: ${{ secrets.AMBER_SSH_KEY }}
      run: |
        poetry install
        echo "$key" > ~/.ssh/id_rsa
        invoke publish