name: Deploy on production

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:

  build:
    name: Build and push statics over ssh
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Poetry install
      run: |
        pip install poetry==1.4.2
        poetry install --no-root
    - name: Deploy
      env:
        SSH_KEY: ${{ secrets.AMBER_SSH_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        ssh-keyscan -H radowit.net > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/known_hosts
        poetry run invoke publish