name: Deploy on production

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build and push statics over ssh
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Poetry install
      run: |
        pip install poetry==1.4.2
        poetry install --no-root
    - name: Deploy
      env:
        key: ${{ secrets.AMBER_SSH_KEY }}
      run: |
        echo "$key" > ~/.ssh/id_rsa
        poetry invoke publish